const topTracks = {
    items:
        [ { album: [Object],
            artists: [Array],
            disc_number: 1,
            duration_ms: 184546,
            explicit: false,
            external_ids: [Object],
            external_urls: [Object],
            href: 'https://api.spotify.com/v1/tracks/5pMs1O32Bm12fGcpIcJh50',
            id: '5pMs1O32Bm12fGcpIcJh50',
            is_playable: true,
            name: 'All Falls Down - Todd Edwards Remix',
            popularity: 49,
            preview_url: 'https://p.scdn.co/mp3-preview/19118b3222a8c2ad3c8c42e5797164226d1a3f7d',
            track_number: 3,
            type: 'track',
            uri: 'spotify:track:5pMs1O32Bm12fGcpIcJh50' },
          { album: [Object],
            artists: [Array],
            disc_number: 1,
            duration_ms: 199765,
            explicit: false,
            external_ids: [Object],
            external_urls: [Object],
            href: 'https://api.spotify.com/v1/tracks/13m97834zAMTGIoW2cHq3W',
            id: '13m97834zAMTGIoW2cHq3W',
            is_playable: true,
            name: 'Big Brown Eyes',
            popularity: 38,
            preview_url: 'https://p.scdn.co/mp3-preview/bd7df37f8c8e8e96e051ffd81d9acedde0dfa909',
            track_number: 1,
            type: 'track',
            uri: 'spotify:track:13m97834zAMTGIoW2cHq3W' },
          { album: [Object],
            artists: [Array],
            disc_number: 1,
            duration_ms: 181466,
            explicit: false,
            external_ids: [Object],
            external_urls: [Object],
            href: 'https://api.spotify.com/v1/tracks/1G8vQSvvw42fseiUPGAVOZ',
            id: '1G8vQSvvw42fseiUPGAVOZ',
            is_playable: true,
            name: 'All We Do For Love',
            popularity: 46,
            preview_url: 'https://p.scdn.co/mp3-preview/6b91a7ed19ab974a66e86d5358f502eb9b651dd5',
            track_number: 5,
            type: 'track',
            uri: 'spotify:track:1G8vQSvvw42fseiUPGAVOZ' },
          { album: [Object],
            artists: [Array],
            disc_number: 1,
            duration_ms: 232560,
            explicit: false,
            external_ids: [Object],
            external_urls: [Object],
            href: 'https://api.spotify.com/v1/tracks/21voxEioZdOUaucmXmMYyS',
            id: '21voxEioZdOUaucmXmMYyS',
            is_playable: true,
            name: 'Each Other',
            popularity: 24,
            preview_url: 'https://p.scdn.co/mp3-preview/7f22d35e982ab0517da65f400c9565a5dbcdfb8b',
            track_number: 8,
            type: 'track',
            uri: 'spotify:track:21voxEioZdOUaucmXmMYyS' },
          { album: [Object],
            artists: [Array],
            disc_number: 1,
            duration_ms: 210199,
            explicit: false,
            external_ids: [Object],
            external_urls: [Object],
            href: 'https://api.spotify.com/v1/tracks/4WVSu8jYqUmj5Hka5kIDy1',
            id: '4WVSu8jYqUmj5Hka5kIDy1',
            is_playable: true,
            name: 'Can We Try',
            popularity: 26,
            preview_url: 'https://p.scdn.co/mp3-preview/ed169fcf61769cf5b995e71c93c0c28d672f11b3',
            track_number: 2,
            type: 'track',
            uri: 'spotify:track:4WVSu8jYqUmj5Hka5kIDy1' },
          { album: [Object],
            artists: [Array],
            disc_number: 1,
            duration_ms: 279226,
            explicit: false,
            external_ids: [Object],
            external_urls: [Object],
            href: 'https://api.spotify.com/v1/tracks/4CNI0d2PFkhVxAljz1S96z',
            id: '4CNI0d2PFkhVxAljz1S96z',
            is_playable: true,
            name: 'Night of the Long Knives',
            popularity: 51,
            preview_url: 'https://p.scdn.co/mp3-preview/3193e7affe32347daef43dd8eeed9f999578dd65',
            track_number: 1,
            type: 'track',
            uri: 'spotify:track:4CNI0d2PFkhVxAljz1S96z' },
          { album: [Object],
            artists: [Array],
            disc_number: 1,
            duration_ms: 185893,
            explicit: false,
            external_ids: [Object],
            external_urls: [Object],
            href: 'https://api.spotify.com/v1/tracks/6HKq2PtG1X7f5QaVBlGTGr',
            id: '6HKq2PtG1X7f5QaVBlGTGr',
            is_playable: true,
            name: 'Realize',
            popularity: 42,
            preview_url: 'https://p.scdn.co/mp3-preview/fd27a505b6f55932b1dfdde0ed9b88fe6a667c0a',
            track_number: 4,
            type: 'track',
            uri: 'spotify:track:6HKq2PtG1X7f5QaVBlGTGr' },
          { album: [Object],
            artists: [Array],
            disc_number: 1,
            duration_ms: 525466,
            explicit: false,
            external_ids: [Object],
            external_urls: [Object],
            href: 'https://api.spotify.com/v1/tracks/6L6BWLhdE9DgpAltnwMqTt',
            id: '6L6BWLhdE9DgpAltnwMqTt',
            is_playable: true,
            name: 'It\'s Just (House of Dupree)',
            popularity: 50,
            preview_url: 'https://p.scdn.co/mp3-preview/1b70d8877cb70e895725062f1cfe13cfd6d24445',
            track_number: 5,
            type: 'track',
            uri: 'spotify:track:6L6BWLhdE9DgpAltnwMqTt' },
          { album: [Object],
            artists: [Array],
            disc_number: 1,
            duration_ms: 285349,
            explicit: false,
            external_ids: [Object],
            external_urls: [Object],
            href: 'https://api.spotify.com/v1/tracks/7jCalGVeStsbqIZ1YGVS7F',
            id: '7jCalGVeStsbqIZ1YGVS7F',
            is_playable: true,
            name: 'Birds of a Feather, We Rock Together',
            popularity: 45,
            preview_url: 'https://p.scdn.co/mp3-preview/a1ceee38466f0192aca0aff065c8fc25bf31c698',
            track_number: 1,
            type: 'track',
            uri: 'spotify:track:7jCalGVeStsbqIZ1YGVS7F' },
          { album: [Object],
            artists: [Array],
            disc_number: 1,
            duration_ms: 319746,
            explicit: false,
            external_ids: [Object],
            external_urls: [Object],
            href: 'https://api.spotify.com/v1/tracks/2cQKF5WKpG6HrKePtXe0fC',
            id: '2cQKF5WKpG6HrKePtXe0fC',
            is_playable: true,
            name: 'Another New Day',
            popularity: 40,
            preview_url: 'https://p.scdn.co/mp3-preview/84d9bc87ab800e4919ae2cc3d72f075527286770',
            track_number: 9,
            type: 'track',
            uri: 'spotify:track:2cQKF5WKpG6HrKePtXe0fC' },
          { album: [Object],
            artists: [Array],
            disc_number: 1,
            duration_ms: 216973,
            explicit: false,
            external_ids: [Object],
            external_urls: [Object],
            href: 'https://api.spotify.com/v1/tracks/4r31J9ZhXbSPqCuEOxJc1U',
            id: '4r31J9ZhXbSPqCuEOxJc1U',
            is_playable: true,
            name: 'Honey Bee',
            popularity: 24,
            preview_url: 'https://p.scdn.co/mp3-preview/437d044e932315b62e0a9910f88bc7ae139c1f76',
            track_number: 3,
            type: 'track',
            uri: 'spotify:track:4r31J9ZhXbSPqCuEOxJc1U' },
          { album: [Object],
            artists: [Array],
            disc_number: 1,
            duration_ms: 140386,
            explicit: false,
            external_ids: [Object],
            external_urls: [Object],
            href: 'https://api.spotify.com/v1/tracks/0eKrGxXCfM2cpCgNi1KPhj',
            id: '0eKrGxXCfM2cpCgNi1KPhj',
            is_playable: true,
            name: 'Dreams',
            popularity: 23,
            preview_url: 'https://p.scdn.co/mp3-preview/75972ba4149fd1b617cd2181d3f0696bf6683d12',
            track_number: 7,
            type: 'track',
            uri: 'spotify:track:0eKrGxXCfM2cpCgNi1KPhj' },
          { album: [Object],
            artists: [Array],
            disc_number: 1,
            duration_ms: 563560,
            explicit: false,
            external_ids: [Object],
            external_urls: [Object],
            href: 'https://api.spotify.com/v1/tracks/1pF80OVKiUppZzVaq2Y9Mk',
            id: '1pF80OVKiUppZzVaq2Y9Mk',
            is_playable: true,
            name: 'Sully Suite',
            popularity: 17,
            preview_url: 'https://p.scdn.co/mp3-preview/29e7753dbaf5e86aea1ad5244ee208fb9e94dee0',
            track_number: 1,
            type: 'track',
            uri: 'spotify:track:1pF80OVKiUppZzVaq2Y9Mk' },
          { album: [Object],
            artists: [Array],
            disc_number: 1,
            duration_ms: 192456,
            explicit: false,
            external_ids: [Object],
            external_urls: [Object],
            href: 'https://api.spotify.com/v1/tracks/4SsTO6IxEQGdmcrVjo34cN',
            id: '4SsTO6IxEQGdmcrVjo34cN',
            is_playable: true,
            linked_from: [Object],
            name: 'King Size',
            popularity: 1,
            preview_url: 'https://p.scdn.co/mp3-preview/fa757312285543f2786d13f208e00bdd1abbd6e5',
            track_number: 1,
            type: 'track',
            uri: 'spotify:track:4SsTO6IxEQGdmcrVjo34cN' },
          { album: [Object],
            artists: [Array],
            disc_number: 3,
            duration_ms: 494466,
            explicit: false,
            external_ids: [Object],
            external_urls: [Object],
            href: 'https://api.spotify.com/v1/tracks/6jXAdaU4wshOAHXCUVvkn3',
            id: '6jXAdaU4wshOAHXCUVvkn3',
            is_playable: true,
            name: 'Cherokee',
            popularity: 42,
            preview_url: 'https://p.scdn.co/mp3-preview/c9ada0064ce05cd126f2ce346889e066d23e0a3d',
            track_number: 2,
            type: 'track',
            uri: 'spotify:track:6jXAdaU4wshOAHXCUVvkn3' },
          { album: [Object],
            artists: [Array],
            disc_number: 1,
            duration_ms: 280626,
            explicit: false,
            external_ids: [Object],
            external_urls: [Object],
            href: 'https://api.spotify.com/v1/tracks/6rbuyK8TNQ72oP2KY52k4d',
            id: '6rbuyK8TNQ72oP2KY52k4d',
            is_playable: true,
            name: 'Rosalinda\'s Eyes',
            popularity: 44,
            preview_url: 'https://p.scdn.co/mp3-preview/c41c0952d64f5b52cdd45b502a15b2cf23818be7',
            track_number: 6,
            type: 'track',
            uri: 'spotify:track:6rbuyK8TNQ72oP2KY52k4d' },
          { album: [Object],
            artists: [Array],
            disc_number: 1,
            duration_ms: 142133,
            explicit: false,
            external_ids: [Object],
            external_urls: [Object],
            href: 'https://api.spotify.com/v1/tracks/33yY3MJYXcPx4MepXMZKCD',
            id: '33yY3MJYXcPx4MepXMZKCD',
            is_playable: true,
            name: 'This Is a Samba',
            popularity: 22,
            preview_url: 'https://p.scdn.co/mp3-preview/3c448fa857bde095608b2a6e0dd223b7f5208faf',
            track_number: 6,
            type: 'track',
            uri: 'spotify:track:33yY3MJYXcPx4MepXMZKCD' },
          { album: [Object],
            artists: [Array],
            disc_number: 1,
            duration_ms: 162585,
            explicit: false,
            external_ids: [Object],
            external_urls: [Object],
            href: 'https://api.spotify.com/v1/tracks/5o4yGlG0PfeVUa6ClIyOxq',
            id: '5o4yGlG0PfeVUa6ClIyOxq',
            is_playable: true,
            name: 'Boys',
            popularity: 77,
            preview_url: 'https://p.scdn.co/mp3-preview/c9b500adf5f76635e064833f77d4ae0983b96c4b',
            track_number: 1,
            type: 'track',
            uri: 'spotify:track:5o4yGlG0PfeVUa6ClIyOxq' },
          { album: [Object],
            artists: [Array],
            disc_number: 1,
            duration_ms: 247426,
            explicit: false,
            external_ids: [Object],
            external_urls: [Object],
            href: 'https://api.spotify.com/v1/tracks/0R863ZR7GlEcQo8Y3RW5Fm',
            id: '0R863ZR7GlEcQo8Y3RW5Fm',
            is_playable: true,
            name: 'Downstream',
            popularity: 22,
            preview_url: 'https://p.scdn.co/mp3-preview/4a9c3e98a81c7c1ec8db1a7821a3e7778e7603cc',
            track_number: 9,
            type: 'track',
            uri: 'spotify:track:0R863ZR7GlEcQo8Y3RW5Fm' },
          { album: [Object],
            artists: [Array],
            disc_number: 1,
            duration_ms: 272869,
            explicit: false,
            external_ids: [Object],
            external_urls: [Object],
            href: 'https://api.spotify.com/v1/tracks/7MNf3gcG2CZARtDcnlJbAY',
            id: '7MNf3gcG2CZARtDcnlJbAY',
            is_playable: true,
            name: 'Beez in the Trap - Instrumental Version',
            popularity: 1,
            preview_url: 'https://p.scdn.co/mp3-preview/55d4112d33d272b7927bf8d18050f8f9e48ac9ee',
            track_number: 29,
            type: 'track',
            uri: 'spotify:track:7MNf3gcG2CZARtDcnlJbAY' } ],
       total: 50,
       limit: 20,
       offset: 0,
       href: 'https://api.spotify.com/v1/me/top/tracks',
       previous: null,
       next: 'https://api.spotify.com/v1/me/top/tracks?limit=20&offset=20' 
}

const artistsByTrackId = [ { external_urls:
  { spotify: 'https://open.spotify.com/artist/7vk5e3vY1uw9plTHJAMwjN' },
  href: 'https://api.spotify.com/v1/artists/7vk5e3vY1uw9plTHJAMwjN',
  id: '7vk5e3vY1uw9plTHJAMwjN',
  name: 'Alan Walker',
  type: 'artist',
  uri: 'spotify:artist:7vk5e3vY1uw9plTHJAMwjN' },
 { external_urls:
  { spotify: 'https://open.spotify.com/artist/55fhWPvDiMpLnE4ZzNXZyW' },
  href: 'https://api.spotify.com/v1/artists/55fhWPvDiMpLnE4ZzNXZyW',
 id: '55fhWPvDiMpLnE4ZzNXZyW',
 name: 'Noah Cyrus',
 type: 'artist',
 uri: 'spotify:artist:55fhWPvDiMpLnE4ZzNXZyW' },
 { external_urls:
  { spotify: 'https://open.spotify.com/artist/5fyDppLDl1juIu1BcUT5zh' },
 href: 'https://api.spotify.com/v1/artists/5fyDppLDl1juIu1BcUT5zh',
 id: '5fyDppLDl1juIu1BcUT5zh',
 name: 'Digital Farm Animals',
 type: 'artist',
 uri: 'spotify:artist:5fyDppLDl1juIu1BcUT5zh' },
 { external_urls:
  { spotify: 'https://open.spotify.com/artist/6MFopqejpmTUUZlcRmGzgg' },
 href: 'https://api.spotify.com/v1/artists/6MFopqejpmTUUZlcRmGzgg',
 id: '6MFopqejpmTUUZlcRmGzgg',
 name: 'Todd Edwards',
 type: 'artist',
 uri: 'spotify:artist:6MFopqejpmTUUZlcRmGzgg' } ]

const topArtists = { items:
  [ { external_urls: [Object],
      followers: [Object],
      genres: [Array],
      href: 'https://api.spotify.com/v1/artists/1HOeqtP7tHkKNJNLzQ2tnr',
      id: '1HOeqtP7tHkKNJNLzQ2tnr',
      images: [Array],
      name: 'Everything Everything',
      popularity: 59,
      type: 'artist',
      uri: 'spotify:artist:1HOeqtP7tHkKNJNLzQ2tnr' },
    { external_urls: [Object],
      followers: [Object],
      genres: [Array],
      href: 'https://api.spotify.com/v1/artists/4gHcu2JoaXJ0mV4aNPCd7N',
      id: '4gHcu2JoaXJ0mV4aNPCd7N',
      images: [Array],
      name: 'Benny Sings',
      popularity: 62,
      type: 'artist',
      uri: 'spotify:artist:4gHcu2JoaXJ0mV4aNPCd7N' },
    { external_urls: [Object],
      followers: [Object],
      genres: [Array],
      href: 'https://api.spotify.com/v1/artists/0mzeuEu2tXNjhVNc1sKVWI',
      id: '0mzeuEu2tXNjhVNc1sKVWI',
      images: [Array],
      name: 'Johnny Green',
      popularity: 53,
      type: 'artist',
      uri: 'spotify:artist:0mzeuEu2tXNjhVNc1sKVWI' },
    { external_urls: [Object],
      followers: [Object],
      genres: [Array],
      href: 'https://api.spotify.com/v1/artists/6nKqt1nbSBEq3iUXD1Xgz8',
      id: '6nKqt1nbSBEq3iUXD1Xgz8',
      images: [Array],
      name: 'Petula Clark',
      popularity: 50,
      type: 'artist',
      uri: 'spotify:artist:6nKqt1nbSBEq3iUXD1Xgz8' },
    { external_urls: [Object],
      followers: [Object],
      genres: [Array],
      href: 'https://api.spotify.com/v1/artists/77bjO3iNEdkJfszgcf6YnB',
      id: '77bjO3iNEdkJfszgcf6YnB',
      images: [Array],
      name: 'Dutch Uncles',
      popularity: 35,
      type: 'artist',
      uri: 'spotify:artist:77bjO3iNEdkJfszgcf6YnB' },
    { external_urls: [Object],
      followers: [Object],
      genres: [Array],
      href: 'https://api.spotify.com/v1/artists/5wZOrGWdg4hq7KIRMupJdI',
      id: '5wZOrGWdg4hq7KIRMupJdI',
      images: [Array],
      name: 'Lone',
      popularity: 47,
      type: 'artist',
      uri: 'spotify:artist:5wZOrGWdg4hq7KIRMupJdI' },
    { external_urls: [Object],
      followers: [Object],
      genres: [Array],
      href: 'https://api.spotify.com/v1/artists/5dyKtXKwZmYhlyh9c6UcB0',
      id: '5dyKtXKwZmYhlyh9c6UcB0',
      images: [Array],
      name: 'Royal Stockholm Philharmonic Orchestra',
      popularity: 47,
      type: 'artist',
      uri: 'spotify:artist:5dyKtXKwZmYhlyh9c6UcB0' },
    { external_urls: [Object],
      followers: [Object],
      genres: [Array],
      href: 'https://api.spotify.com/v1/artists/2Jv5eshHtLycR6R8KQCdc4',
      id: '2Jv5eshHtLycR6R8KQCdc4',
      images: [Array],
      name: 'Grizzly Bear',
      popularity: 67,
      type: 'artist',
      uri: 'spotify:artist:2Jv5eshHtLycR6R8KQCdc4' },
    { external_urls: [Object],
      followers: [Object],
      genres: [Array],
      href: 'https://api.spotify.com/v1/artists/1P6U1dCeHxPui5pIrGmndZ',
      id: '1P6U1dCeHxPui5pIrGmndZ',
      images: [Array],
      name: 'Air',
      popularity: 64,
      type: 'artist',
      uri: 'spotify:artist:1P6U1dCeHxPui5pIrGmndZ' },
    { external_urls: [Object],
      followers: [Object],
      genres: [Array],
      href: 'https://api.spotify.com/v1/artists/0f3PsS9IQ6whvNMFFKnpjl',
      id: '0f3PsS9IQ6whvNMFFKnpjl',
      images: [Array],
      name: 'Choir of King\'s College, Cambridge',
      popularity: 67,
      type: 'artist',
      uri: 'spotify:artist:0f3PsS9IQ6whvNMFFKnpjl' },
    { external_urls: [Object],
      followers: [Object],
      genres: [Array],
      href: 'https://api.spotify.com/v1/artists/1z9u3vLr7gw6IBS8CP8c2X',
      id: '1z9u3vLr7gw6IBS8CP8c2X',
      images: [Array],
      name: 'BBC Philharmonic Orchestra',
      popularity: 50,
      type: 'artist',
      uri: 'spotify:artist:1z9u3vLr7gw6IBS8CP8c2X' },
    { external_urls: [Object],
      followers: [Object],
      genres: [Array],
      href: 'https://api.spotify.com/v1/artists/2o7L9DNcmzocYll1o0GGTU',
      id: '2o7L9DNcmzocYll1o0GGTU',
      images: [Array],
      name: 'Leon Vynehall',
      popularity: 48,
      type: 'artist',
      uri: 'spotify:artist:2o7L9DNcmzocYll1o0GGTU' },
    { external_urls: [Object],
      followers: [Object],
      genres: [Array],
      href: 'https://api.spotify.com/v1/artists/2WoVwexZuODvclzULjPQtm',
      id: '2WoVwexZuODvclzULjPQtm',
      images: [Array],
      name: 'Sampha',
      popularity: 71,
      type: 'artist',
      uri: 'spotify:artist:2WoVwexZuODvclzULjPQtm' },
    { external_urls: [Object],
      followers: [Object],
      genres: [Array],
      href: 'https://api.spotify.com/v1/artists/57vWImR43h4CaDao012Ofp',
      id: '57vWImR43h4CaDao012Ofp',
      images: [Array],
      name: 'Steve Lacy',
      popularity: 68,
      type: 'artist',
      uri: 'spotify:artist:57vWImR43h4CaDao012Ofp' },
    { external_urls: [Object],
      followers: [Object],
      genres: [Array],
      href: 'https://api.spotify.com/v1/artists/1m4GViPjIy4T8Pd0Iz6hRS',
      id: '1m4GViPjIy4T8Pd0Iz6hRS',
      images: [Array],
      name: 'Ian Pooley',
      popularity: 40,
      type: 'artist',
      uri: 'spotify:artist:1m4GViPjIy4T8Pd0Iz6hRS' },
    { external_urls: [Object],
      followers: [Object],
      genres: [Array],
      href: 'https://api.spotify.com/v1/artists/1j8m5isW09lzbcz5kcUADT',
      id: '1j8m5isW09lzbcz5kcUADT',
      images: [Array],
      name: 'Jett Rebel',
      popularity: 42,
      type: 'artist',
      uri: 'spotify:artist:1j8m5isW09lzbcz5kcUADT' },
    { external_urls: [Object],
      followers: [Object],
      genres: [Array],
      href: 'https://api.spotify.com/v1/artists/1pVtwG5Up1OZOEpSHJ4AAs',
      id: '1pVtwG5Up1OZOEpSHJ4AAs',
      images: [Array],
      name: 'Buddy Rich',
      popularity: 46,
      type: 'artist',
      uri: 'spotify:artist:1pVtwG5Up1OZOEpSHJ4AAs' },
    { external_urls: [Object],
      followers: [Object],
      genres: [Array],
      href: 'https://api.spotify.com/v1/artists/25uiPmTg16RbhZWAqwLBy5',
      id: '25uiPmTg16RbhZWAqwLBy5',
      images: [Array],
      name: 'Charli XCX',
      popularity: 82,
      type: 'artist',
      uri: 'spotify:artist:25uiPmTg16RbhZWAqwLBy5' },
    { external_urls: [Object],
      followers: [Object],
      genres: [Array],
      href: 'https://api.spotify.com/v1/artists/6gkWznnJkdkwRPVcmnrays',
      id: '6gkWznnJkdkwRPVcmnrays',
      images: [Array],
      name: 'Sister Sledge',
      popularity: 62,
      type: 'artist',
      uri: 'spotify:artist:6gkWznnJkdkwRPVcmnrays' },
    { external_urls: [Object],
      followers: [Object],
      genres: [Array],
      href: 'https://api.spotify.com/v1/artists/2mVVjNmdjXZZDvhgQWiakk',
      id: '2mVVjNmdjXZZDvhgQWiakk',
      images: [Array],
      name: 'Khruangbin',
      popularity: 62,
      type: 'artist',
      uri: 'spotify:artist:2mVVjNmdjXZZDvhgQWiakk' } ],
 total: 50,
 limit: 20,
 offset: 0,
 href: 'https://api.spotify.com/v1/me/top/artists',
 previous: null,
 next: 'https://api.spotify.com/v1/me/top/artists?limit=20&offset=20' }

module.exports = {topTracks, artistsByTrackId, topArtists}